vdso32: Fix compilation errors with Android clang
/usr/bin/as: unrecognized option '-EL'
clang-15: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../arch/arm64/kernel/vdso32/Makefile:148: arch/arm64/kernel/vdso32/sigreturn.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/usr/bin/as: unrecognized option '-EL'
clang-15: error: assembler command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../arch/arm64/kernel/vdso32/Makefile:146: arch/arm64/kernel/vdso32/vgettimeofday.o] Error 1
make[1]: *** [arch/arm64/Makefile:239: vdso_prepare] Error 2
make[1]: Leaving directory '/workspace/unitrix/out'
make: *** [Makefile:154: sub-make] Error 2

Signed-off-by: GhostMaster69-dev <rathore6375@gmail.com>

1 parent e3dc2c6 commit e4d868283173869ad82ce556551bd7eca0ca0cce